"""E2 generation-pipeline harness - runs the real generators SAFELY.

    python test/edits_pipeline_test.py             # equals gate: empty edits must reproduce the
                                                   # reproducible baseline byte-for-byte (SHA-256)
    python test/edits_pipeline_test.py --fixture   # smoke run with test/fixtures/edits_sample.json;
                                                   # C02 asserts forest.add/remove and water.add change
                                                   # ground/terrain/collision in the expected windows

Safety model
------------
The generators write to fixed paths in docs/ (docs/map.json, docs/items.json,
docs/img/map_*.png) and do not yet support an output-directory override, so the
harness uses full backup/restore:

  1. SHA-256 every protected output and copy it into a temp backup dir
     (TMPDIR -> Hermes scratch on this machine, pruned after 24 h);
  2. run `python osm/render_map.py` then `python osm/place_items.py` in the
     worktree root with ARK_EDITS pointing at a fixture;
  3. equals gate: assert post-run bytes == EXPECTED_BASELINE below (the empty-
     edits output measured during C01, deterministically reproducible);
  4. restore the originals from the backup in a `finally` and PROVE the
     restoration with hashes before exiting - even when a step above failed.

Both modes must exit with the real docs/ files byte-identical to how they were
found. Phase C is serialized on the map (exclusive lock), so no concurrent
writer can touch docs/ while this test runs. The equals gate sets ARK_EDITS to
the EMPTY fixture on purpose: the gate stays hermetic no matter what
osm/edits.json contains in the worktree ("empty or missing edits must leave
every output unchanged").

Baseline reproducibility note (measured 2026-09-29, C01)
--------------------------------------------------------
EXPECTED_BASELINE was captured by running the pipeline twice with EMPTY edits
(full render + isolated place_items rerun against restored committed inputs);
both runs were byte-identical. docs/map.json matches the committed bytes, but
the committed items.json and the four PNGs do NOT (PNG difference is encoding
only: identical decoded pixels, P vs L mode / palette emitted by this PIL;
items.json difference is real content - see below). A WARNING is printed when
the pre-run docs/ state differs from EXPECTED_BASELINE; the gate still passes
as long as the re-render is deterministic and the originals are restored.

The committed items.json was NOT produced by the current osm/ code in this
environment: running place_items.py on the exact committed map.json + PNGs
yields the regenerated bytes (e6d79b49...), not the committed ones
(355d71f1...). osm/ is unchanged since the last docs commit (61bfd91), so the
drift comes from the environment (most likely numpy 2.x's changed default sort
kind; it re-orders equally-good candidate spots in near_free/board placement).
C02 must regenerate and commit docs/ (or pin the gate to decoded equality)
as part of landing its hooks.

Exit code: 0 all good, 1 any failure.
"""
import glob, hashlib, json, os, shutil, subprocess, sys, tempfile

sys.stdout.reconfigure(encoding='utf-8', errors='replace')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, 'osm'))
from geo import P as _P  # fixture lat/lon -> art pixels, so the assertion boxes follow the map geometry

PROTECTED = ['docs/map.json', 'docs/items.json'] + \
            sorted(glob.glob('docs/img/map_*.png'))
PROTECTED = [p.replace(os.sep, '/') for p in PROTECTED]  # glob yields \\ on Windows
EMPTY_FIXTURE = os.path.join(ROOT, 'test', 'fixtures', 'edits_empty.json')
SAMPLE_FIXTURE = os.path.join(ROOT, 'test', 'fixtures', 'edits_sample.json')
TIMEOUT = 1800  # seconds per generator step (map is 5143x7091 px)

# Reproducible empty-edits output of the CURRENT generator code in THIS env
# (PIL 12.3.0, numpy 2.4.4, scipy 1.18.1). Verify determinism with a rerun.
EXPECTED_BASELINE = {
    'docs/map.json':               'bab80dcb282f957c5accb25cb7f0963c18090136019e5ac7fd0ecb0c2d9614a7',
    'docs/items.json':             'e6d79b49a2c3e74474896f78b682b583b46c6446fe24245eb85efe00a5dae6f6',
    'docs/img/map_collide.png':    '8a99214d494880fc0dac2b5849509cf05aa1558c9a481a6f7cd21b1eae31c516',
    'docs/img/map_ground.png':     'c0f510008652ba20ab324b331028b208b9551d0a794e5224d17c0a07772d73a8',
    'docs/img/map_objects.png':    '3213eda3854b00c50eff69d2a603d1e164edd166305975a92b186cc979b2e084',
    'docs/img/map_terrain.png':    'aabc7d6f7da8152eae36accedc76f8f0627cccd93bbd7a646955316758d38efe',
}

fails = []
warns = []


def check(cond, msg):
    print(('ok   ' if cond else 'FAIL ') + msg)
    if not cond:
        fails.append(msg)


def sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(1 << 20), b''):
            h.update(chunk)
    return h.hexdigest()


def rel_key(rel):
    return rel.replace('/', '__')


def run_pipeline(edits_path):
    """Run render_map.py then place_items.py with ARK_EDITS set. Returns [(cmd, rc, tail), ...] for failures only."""
    env = dict(os.environ, ARK_EDITS=edits_path, PYTHONIOENCODING='utf-8')
    bad = []
    for script in ('osm/render_map.py', 'osm/place_items.py'):
        print(f'-- running: {sys.executable} {script}')
        p = subprocess.run([sys.executable, script], cwd=ROOT, env=env,
                           capture_output=True, text=True, timeout=TIMEOUT)
        tail = ((p.stdout or '') + (p.stderr or ''))[-800:].replace('\n', ' | ')
        if tail.strip():
            print('   tail:', tail[-600:])
        if p.returncode:
            bad.append((script, p.returncode, tail))
    return bad


# ---------------------------------------------------------------- C02 assertions
# Fixture content windows (derived from the sample fixture's lat/lon polygons via
# geo.P, so they follow the map if the bbox ever moves):
#   forest.add   (2360, 2960)-(2440, 3040)  - open grass today, becomes forest floor
#   forest.remove (2390, 2989)-(2410, 3010) - hole INSIDE forest.add, must stay grass
#   water.add    (2969, 3570)-(3029, 3630)  - open grass today, becomes a pond
FOREST_FILL = (31, 79, 36)          # exact hexc('#1f4f24') forest-floor base


def _fixture_layout():
    """Pixel boxes (y0, x0, y1, x1) of the sample fixture's forest/water polygons."""
    data = json.load(open(SAMPLE_FIXTURE, encoding='utf-8'))
    def poly(layer, key):
        return data['layers'][layer][key][0]['poly']
    def box(points, pad):
        xs = [_P(lat, lon)[0] for lat, lon in points]
        ys = [_P(lat, lon)[1] for lat, lon in points]
        return (int(min(ys)) - pad, int(min(xs)) - pad,
                int(max(ys)) + 1 + pad, int(max(xs)) + 1 + pad)
    return box(poly('forest', 'add'), 2), box(poly('forest', 'remove'), 0), box(poly('water', 'add'), 2)


def _map_stats(boxes, outdir=None):
    """Count forest-fill/terrain-220/water-blue/collide pixels in the fixture windows.
    When outdir is given, save before/after crops of each window there (2x scale)."""
    import numpy as np
    from PIL import Image
    g = np.array(Image.open('docs/img/map_ground.png').convert('RGB'))
    t = np.array(Image.open('docs/img/map_terrain.png').convert('L'))
    c = np.array(Image.open('docs/img/map_collide.png').convert('L'))
    fa, hole, wa = boxes
    fill = (g[..., 0] == FOREST_FILL[0]) & (g[..., 1] == FOREST_FILL[1]) & (g[..., 2] == FOREST_FILL[2])
    blue = (g[..., 2] > g[..., 0] + 20) & (g[..., 2] > g[..., 1] + 10)
    def terr(box):
        y0, x0, y1, x1 = box
        return t[y0 // 4:y1 // 4, x0 // 4:x1 // 4]
    stats = dict(
        fa_fill=int(fill[fa[0]:fa[2], fa[1]:fa[3]].sum()),
        fa_t220=int((terr(fa) == 220).sum()),
        hole_t220=int((terr(hole) == 220).sum()),
        # Interior of the remove polygon: skip the 1-px north edge row - the
        # remove polygon's top edge sits exactly on a pixel boundary (y=2990.0),
        # and the pixel-centre rasteriser legitimately keeps that row. The true
        # signal is that everything >= 1 px inside the polygon is not forest.
        hole_fill=int(fill[hole[0] + 2:hole[2], hole[1] + 1:hole[3] - 1].sum()),
        wa_blue=int(blue[wa[0]:wa[2], wa[1]:wa[3]].sum()),
        wa_c255=int((c[wa[0]:wa[2], wa[1]:wa[3]] == 255).sum()),
        wa_c128=int((c[wa[0]:wa[2], wa[1]:wa[3]] == 128).sum()),
    )
    if outdir:
        os.makedirs(outdir, exist_ok=True)
        ar = lambda a, box: Image.fromarray(a[box[0]:box[2], box[1]:box[3]]).resize(
            ((box[3] - box[1]) * 2, (box[2] - box[0]) * 2), Image.Resampling.NEAREST)
        ar(g, wa).save(os.path.join(outdir, 'water_ground.png'))
        ar(c, wa).save(os.path.join(outdir, 'water_collide.png'))
        ar(g, fa).save(os.path.join(outdir, 'forest_ground.png'))
        ar(t, (fa[0] // 4, fa[1] // 4, fa[2] // 4, fa[3] // 4)).save(os.path.join(outdir, 'forest_terrain.png'))
    return stats


def main():
    fixture_mode = '--fixture' in sys.argv
    backup_dir = tempfile.mkdtemp(prefix='chlopkow-pipeline-')
    print('worktree:', ROOT)
    print('backup dir:', backup_dir)
    print(f'protected outputs ({len(PROTECTED)}):', *PROTECTED, sep='\n  ')

    before = {}
    for rel in PROTECTED:
        dst = os.path.join(backup_dir, rel_key(rel))
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(rel, dst)
        before[rel] = sha256(rel)

    drift = [rel for rel in PROTECTED if before[rel] != EXPECTED_BASELINE.get(rel)]
    if drift:
        warns.append('pre-run docs/ state differs from the reproducible baseline '
                     '(stale committed outputs): ' + ', '.join(drift))
        for rel in drift:
            print(f'WARN  {rel}\n      found    {before[rel]}\n      expected {EXPECTED_BASELINE.get(rel)}')

    try:
        if fixture_mode:
            check(os.path.exists(SAMPLE_FIXTURE), 'fixture test/fixtures/edits_sample.json exists')
            boxes = _fixture_layout()
            crops_dir = os.path.join(backup_dir, 'fixture-crops')
            st0 = _map_stats(boxes, os.path.join(crops_dir, 'before'))   # committed/today's pixels
            bad = run_pipeline(SAMPLE_FIXTURE)
            check(not bad, f'pipeline completed with SAMPLE edits ({len(bad)} failing step(s))')
            if bad:
                for s, rc, t in bad:
                    print(f'   {s} exit {rc}: {t}')
            st = _map_stats(boxes, os.path.join(crops_dir, 'after'))     # fixture-run pixels
            # C02 forest/water content assertions (trees + entities arrive with C03/C04).
            check(st0['fa_fill'] < 100 and st0['fa_t220'] < 50,
                  'fixture forest box starts on open grass (window not already forest)')
            check(st0['wa_blue'] < 100 and st0['wa_c255'] < 100,
                  'fixture water box starts on open grass (window not already water)')
            check(st['fa_fill'] - st0['fa_fill'] >= 2000,
                  f'forest.add paints forest floor colour in map_ground.png ({st0["fa_fill"]} -> {st["fa_fill"]} px)')
            check(st['fa_t220'] >= 300,
                  f'forest.add sets terrain class 220 on map_terrain.png ({st["fa_t220"]} px)')
            check(st['hole_t220'] == 0,
                  f'forest.remove restores grass terrain class in the clear polygon ({st["hole_t220"]} px of 220)')
            check(st['hole_fill'] <= 50,
                  f'forest.remove clears forest floor colour inside the clear polygon ({st["hole_fill"]} px)')
            check(st['wa_blue'] - st0['wa_blue'] >= 2500,
                  f'water.add paints water colour on map_ground.png ({st0["wa_blue"]} -> {st["wa_blue"]} px)')
            check(st['wa_c255'] - st0['wa_c255'] >= 3400,
                  f'water.add marks solid collision 255 on map_collide.png ({st0["wa_c255"]} -> {st["wa_c255"]} px)')
            check(st['wa_c128'] == 0,
                  f'water.add collision is solid 255, not low/jumpable 128 ({st["wa_c128"]} px)')
            print('fixture window crops (before/after) in:', crops_dir)
        else:
            check(os.path.exists(EMPTY_FIXTURE), 'fixture test/fixtures/edits_empty.json exists')
            bad = run_pipeline(EMPTY_FIXTURE)
            check(not bad, f'pipeline completed with EMPTY edits ({len(bad)} failing step(s))')
            if bad:
                for s, rc, t in bad:
                    print(f'   {s} exit {rc}: {t}')
            for rel in PROTECTED:
                after = sha256(rel)
                check(after == EXPECTED_BASELINE[rel],
                      f'empty-edits run reproduces baseline: {rel}')
                if after != EXPECTED_BASELINE[rel]:
                    print(f'   {rel}: expected {EXPECTED_BASELINE[rel]} -> got {after}')
    finally:
        # restore originals no matter what happened above, then prove it
        for rel in PROTECTED:
            shutil.copy2(os.path.join(backup_dir, rel_key(rel)), rel)
        restored = {rel: sha256(rel) for rel in PROTECTED}
        for rel in PROTECTED:
            check(restored[rel] == before[rel], f'originals restored byte-identical: {rel}')

    for w in warns:
        print('WARN ', w)
    print('\nFAILED:', len(fails)) if fails else print('\nALL PASSED')
    print('committed baseline hashes (scratch: C:\\Users\\Lenovo\\AppData\\Local\\hermes\\cache\\scratch\\chlopkow-c01\\baseline.sha256):')
    for rel in PROTECTED:
        print(f'  {before[rel]}  {rel}')
    sys.exit(1 if fails else 0)


if __name__ == '__main__':
    main()