"""Manual map edits applied on top of the OSM-generated map.

The map stays generated by osm/render_map.py + osm/place_items.py. Hand corrections
(trees, woods, ponds, collision, entity positions, zones) live as data in
osm/edits.json and are applied at fixed pipeline stages. Every coordinate is stored as
lat/lon, so edits survive any future change of the map bbox or scale.

Pipeline contract (hooked into the generators later, see plans/2026-09-28-map-editor.md):

    import edits
    EDITS = edits.load()                       # missing file -> empty edits
    edits.apply('forest', EDITS, ctx)          # ctx = dict of the generator's arrays/lists

Stages and the ctx keys they use:
    forest      forest_mask (bool HxW)                     forest.add / forest.remove
    trees       tree_pts (list of (x, y, r, dark)), W, H   trees.clear / trees.add (adds `keep` flag list)
    water       pond_m (bool HxW), collide (bool HxW)      water.add
    collision   collide_img (uint8 HxW: 0/128/255), road_m   collision.block / collision.free
        entities    target (dict 'kind:id' -> the generator's own record dict with x/y),
                target_list (the generator's list of those same records)
                entities.<kind>:<id> = {lat, lon, ...freely replaced fields...} moves the
                  entity to the EXACT lat/lon (unknown id raises); entities.remove =
                  ['kind:id', ...] drops records (unknown raises); entities.add =
                  [{kind, id, lat, lon, ...}] appends a new record at its exact lat/lon.
    buildings   buildings (generator list of dicts: id, kind, c, ax, nx, L, Wd)
                                                            buildings.remove / .modify / .add
                (hook right after the OSM building list is built, before footprint fitting;
                 records with fixed=True must keep their size: skip the 1.25-2.3x exaggeration)
    zones       target / target_list, venues (dict venue-name -> (x, y) px anchor),
                spot (callable anchor -> reachable {x, y}, generator's own spot finder)
                zones.items[] with kind 'people' and props {npc: id, venue: key} move that
                npc to the venue anchor (snapped to reachable ground); music/animals/custom
                zones stay runtime-only data.

An empty or missing edits file must leave every output unchanged.
"""
import copy
import json
import math
import os
import tempfile

import numpy as np

try:
    import geo
except ImportError:  # imported as osm.edits from the project root
    from osm import geo

VERSION = 1
DEFAULT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'edits.json')
ZONE_KINDS = ('music', 'animals', 'people', 'custom')
BUILDING_KINDS = ('house', 'farm')


# ---------------------------------------------------------------- geometry

def to_px(lat, lon):
    """lat/lon -> art pixels of the current map (floats)."""
    return geo.P(lat, lon)


def to_ll(x, y):
    """art pixels of the current map -> (lat, lon)."""
    return geo.to_latlon(x, y)


def poly_px(poly):
    return [to_px(lat, lon) for lat, lon in poly]


def poly_window_mask(poly, W, H, pad=2):
    """Rasterise a lat/lon polygon. Returns (x0, y0, mask) clipped to the map, or None
    when the polygon is fully outside. Uses even-odd point-in-polygon on pixel centres."""
    pts = np.array(poly_px(poly), dtype=np.float64)
    x0 = max(0, int(math.floor(pts[:, 0].min())) - pad)
    y0 = max(0, int(math.floor(pts[:, 1].min())) - pad)
    x1 = min(W, int(math.ceil(pts[:, 0].max())) + pad + 1)
    y1 = min(H, int(math.ceil(pts[:, 1].max())) + pad + 1)
    if x1 <= x0 or y1 <= y0:
        return None
    yy, xx = np.mgrid[y0:y1, x0:x1]
    px, py = xx + .5, yy + .5
    inside = np.zeros(px.shape, bool)
    n = len(pts)
    for i in range(n):
        ax, ay = pts[i]
        bx, by = pts[(i + 1) % n]
        if ay == by:
            continue
        cond = (ay > py) != (by > py)
        xint = ax + (py - ay) * (bx - ax) / (by - ay)
        inside ^= cond & (px < xint)
    return x0, y0, inside


def paint(mask, poly, value=True):
    """Set mask pixels inside a lat/lon polygon to `value` (in place)."""
    H, W = mask.shape
    r = poly_window_mask(poly, W, H)
    if r is None:
        return mask
    x0, y0, m = r
    mask[y0:y0 + m.shape[0], x0:x0 + m.shape[1]][m] = value
    return mask


def point_in_poly(x, y, poly):
    pts = poly_px(poly)
    inside = False
    for i in range(len(pts)):
        ax, ay = pts[i]
        bx, by = pts[(i + 1) % len(pts)]
        if (ay > y) != (by > y) and x < ax + (y - ay) * (bx - ax) / (by - ay):
            inside = not inside
    return inside


# ---------------------------------------------------------------- validation

def _num(v):
    return isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v)


def _latlon_errors(o, where):
    errs = []
    if not (_num(o.get('lat')) and -90 <= o['lat'] <= 90):
        errs.append(f'{where}: lat must be a number in [-90, 90]')
    if not (_num(o.get('lon')) and -180 <= o['lon'] <= 180):
        errs.append(f'{where}: lon must be a number in [-180, 180]')
    return errs


def _poly_errors(o, where):
    p = o.get('poly') if isinstance(o, dict) else None
    if not isinstance(p, list) or len(p) < 3:
        return [f'{where}: poly must be a list of at least 3 [lat, lon] points']
    for i, v in enumerate(p):
        if not (isinstance(v, (list, tuple)) and len(v) == 2 and _num(v[0]) and _num(v[1])):
            return [f'{where}.poly[{i}]: expected [lat, lon]']
    return []


def _list(layer, key, where, item_check):
    v = layer.get(key, [])
    if not isinstance(v, list):
        return [f'{where}.{key}: must be a list']
    errs = []
    for i, o in enumerate(v):
        if not isinstance(o, dict):
            errs.append(f'{where}.{key}[{i}]: must be an object')
        else:
            errs += item_check(o, f'{where}.{key}[{i}]')
    return errs


def _v_trees(layer, w):
    def tree(o, where):
        e = _latlon_errors(o, where)
        if 'r' in o and not (_num(o['r']) and 3 <= o['r'] <= 40):
            e.append(f'{where}: r must be a number in [3, 40]')
        if 'dark' in o and not isinstance(o['dark'], bool):
            e.append(f'{where}: dark must be true/false')
        return e
    return _list(layer, 'add', w, tree) + _list(layer, 'clear', w, _poly_errors)


def _v_forest(layer, w):
    return _list(layer, 'add', w, _poly_errors) + _list(layer, 'remove', w, _poly_errors)


def _v_water(layer, w):
    return _list(layer, 'add', w, _poly_errors)


def _v_collision(layer, w):
    return _list(layer, 'block', w, _poly_errors) + _list(layer, 'free', w, _poly_errors)


def _v_entities(layer, w):
    errs = []
    for k, o in layer.items():
        if k in ('add', 'remove'):
            continue            # handled below
        if ':' not in k:
            errs.append(f'{w}.{k}: key must look like kind:id, e.g. npc:soltys')
        elif not isinstance(o, dict):
            errs.append(f'{w}.{k}: must be an object')
        else:
            errs += _latlon_errors(o, f'{w}.{k}')
    def entity(o, where):
        e = _latlon_errors(o, where)
        if not (isinstance(o.get('kind'), str) and o.get('kind')
                and isinstance(o.get('id'), str) and o.get('id')):
            e.append(f'{where}: kind and id (non-empty strings) are required')
        return e
    errs += _list(layer, 'add', w, entity)
    rm = layer.get('remove', [])
    if not isinstance(rm, list) or not all(isinstance(i, str) and ':' in i for i in rm):
        errs.append(f'{w}.remove: must be a list of kind:id strings (e.g. "npc:halina")')
    return errs


def _v_zones(layer, w):
    def zone(o, where):
        e = _poly_errors(o, where)
        if o.get('kind') not in ZONE_KINDS:
            e.append(f'{where}: kind must be one of {", ".join(ZONE_KINDS)}')
        if not isinstance(o.get('id', ''), str) or not o.get('id'):
            e.append(f'{where}: id must be a non-empty string')
        if 'props' in o and not isinstance(o['props'], dict):
            e.append(f'{where}: props must be an object')
        return e
    return _list(layer, 'items', w, zone)


def _v_buildings(layer, w):
    errs = []

    def rect(o, where):
        e = _latlon_errors(o, where)
        for k, lo, hi in (('len', 1, 300), ('wid', 1, 300)):
            if not (_num(o.get(k)) and lo <= o[k] <= hi):
                e.append(f'{where}: {k} (metres) must be a number in [{lo}, {hi}]')
        if 'angle' in o and not (_num(o['angle']) and -360 <= o['angle'] <= 360):
            e.append(f'{where}: angle (degrees) must be in [-360, 360]')
        if 'kind' in o and o['kind'] not in BUILDING_KINDS:
            e.append(f'{where}: kind must be one of {", ".join(BUILDING_KINDS)}')
        return e
    errs += _list(layer, 'add', w, rect)
    rm = layer.get('remove', [])
    if not isinstance(rm, list) or not all(isinstance(i, int) and not isinstance(i, bool) for i in rm):
        errs.append(f'{w}.remove: must be a list of OSM way ids (integers)')
    mod = layer.get('modify', {})
    if not isinstance(mod, dict):
        errs.append(f'{w}.modify: must be an object keyed by OSM way id')
    else:
        for k, o in mod.items():
            if not str(k).isdigit():
                errs.append(f'{w}.modify.{k}: key must be an OSM way id')
            elif not isinstance(o, dict):
                errs.append(f'{w}.modify.{k}: must be an object')
            else:
                errs += rect(o, f'{w}.modify.{k}')
    return errs


def building_record(o, bid, kind='house'):
    """Edit rectangle (centre lat/lon, len/wid metres, angle degrees) -> generator building dict.
    `fixed` means: use this exact size, do not apply the generator's footprint exaggeration."""
    cx, cy = to_px(o['lat'], o['lon'])
    a = math.radians(o.get('angle', 0))
    ax, nx = np.array([math.cos(a), math.sin(a)]), np.array([-math.sin(a), math.cos(a)])
    return dict(id=bid, kind=o.get('kind', kind), c=np.array([cx, cy]), ax=ax, nx=nx,
                L=float(o['len']) * geo.A, Wd=float(o['wid']) * geo.A, fixed=True)


def _a_buildings(layer, ctx):
    bl = ctx['buildings']
    removed = set(layer.get('remove', []))
    mod = {int(k): v for k, v in layer.get('modify', {}).items()}
    out = []
    for b in bl:
        if b['id'] in removed:
            continue
        if b['id'] in mod:
            b = dict(b, **building_record(mod[b['id']], b['id'], b.get('kind', 'house')))
        out.append(b)
    for i, o in enumerate(layer.get('add', [])):
        out.append(building_record(o, o.get('id') or f'edit:{i}'))
    bl[:] = out


# ---------------------------------------------------------------- appliers

def _a_forest(layer, ctx):
    fm = ctx['forest_mask']
    for o in layer.get('add', []):
        paint(fm, o['poly'], True)
    for o in layer.get('remove', []):
        paint(fm, o['poly'], False)


def _a_trees(layer, ctx):
    pts = ctx['tree_pts']
    clears = layer.get('clear', [])
    if clears:
        pts[:] = [t for t in pts if not any(point_in_poly(t[0], t[1], c['poly']) for c in clears)]
    keep = ctx.setdefault('tree_keep', [])
    for o in layer.get('add', []):
        x, y = to_px(o['lat'], o['lon'])
        t = (float(x), float(y), float(o.get('r', 11)), bool(o.get('dark', False)))
        pts.append(t)
        keep.append(t)


def _a_water(layer, ctx):
    for o in layer.get('add', []):
        paint(ctx['pond_m'], o['poly'], True)
        if 'collide' in ctx:
            paint(ctx['collide'], o['poly'], True)


def _a_collision(layer, ctx):
    img = ctx['collide_img']
    for o in layer.get('block', []):
        paint(img, o['poly'], 255)
    for o in layer.get('free', []):
        paint(img, o['poly'], 0)
    if ctx.get('road_m') is not None:
        img[ctx['road_m']] = 0          # roads and tracks always stay walkable


def _a_entities(layer, ctx):
    """Move existing entities, add new ones and drop others, all in place.

    ctx['target'] maps 'kind:id' -> the GENERATOR's own record dict; ctx['target_list']
    is the generator's collection holding those same dict objects, so append/remove
    keep the generator's list as the single source of truth. Overrides and adds place
    the entity at the EXACT lat/lon - the generator must check reachability (a pin
    drawn by an editor on a blocked spot fails loudly in the pipeline instead of
    being silently re-snapped by a later at() call). Unknown ids RAISE: a typo in the
    edits file must break the build, not move the wrong (or no) entity.
    """
    target = ctx['target']
    tlist = ctx.get('target_list')
    for k, o in layer.items():
        if k in ('add', 'remove'):
            continue
        if k not in target:
            raise ValueError(f'entities.{k}: unknown entity (known ids: {sorted(target)})')
        rec = target[k]
        x, y = to_px(o['lat'], o['lon'])
        rec.update(x=int(round(x)), y=int(round(y)),
                   **{kk: vv for kk, vv in o.items() if kk not in ('lat', 'lon')})
    for k in layer.get('remove', []):
        if k not in target:
            raise ValueError(f'entities.remove: unknown entity {k!r} (known ids: {sorted(target)})')
        if tlist is not None:
            tlist.remove(target[k])
        del target[k]
    for o in layer.get('add', []):
        key = f"{o['kind']}:{o['id']}"
        if key in target:
            raise ValueError(f'entities.add {key}: already exists - use the "kind:id" override form to move it')
        x, y = to_px(o['lat'], o['lon'])
        rec = dict(id=o['id'], x=int(round(x)), y=int(round(y)),
                   **{kk: vv for kk, vv in o.items() if kk not in ('kind', 'id', 'lat', 'lon')})
        target[key] = rec
        if tlist is not None:
            tlist.append(rec)


def _a_zones(layer, ctx):
    """People zones can move their NPC to a venue anchor; music/animals/custom zones
    stay runtime-only data.

    A zone item with kind 'people' and props {'npc': id, 'venue': key} relocates that
    npc to the venue's anchor. When ctx['spot'] (the generator's own reachable-spot
    finder, usually its at()) is provided, the npc is snapped to reachable ground near
    the anchor; otherwise it is placed on the anchor pixel itself. Unknown npc ids and
    venue names raise - the pipeline fails loudly instead of silently ignoring a typo.
    """
    target = ctx.get('target') or {}
    venues = ctx.get('venues') or {}
    spot = ctx.get('spot')
    for z in layer.get('items', []):
        p = z.get('props') or {}
        nid, ven = p.get('npc'), p.get('venue')
        if not nid or not ven:
            continue            # zone without a move directive is runtime data
        zid = z.get('id') or '?'
        if z.get('kind') != 'people':
            raise ValueError(f'zones.{zid}: zone->npc moves need kind "people" (got {z.get("kind")!r})')
        key = nid if ':' in nid else f'npc:{nid}'
        if key not in target:
            raise ValueError(f'zones.{zid}: unknown npc {nid!r} (known ids: {sorted(target)})')
        if ven not in venues:
            raise ValueError(f'zones.{zid}: unknown venue {ven!r} (known: {sorted(venues)})')
        if spot is not None:
            target[key].update(spot(*venues[ven]))
        else:
            x, y = venues[ven]
            target[key].update(x=int(round(x)), y=int(round(y)))


class LayerSpec:
    def __init__(self, validate, stage=None, apply=None, empty=None):
        self.validate, self.stage, self.apply = validate, stage, apply
        self.empty = empty if empty is not None else {}


# New edit types: add one entry here (+ an editor tool in editor/tools/).
LAYERS = {
    'trees': LayerSpec(_v_trees, 'trees', _a_trees),
    'forest': LayerSpec(_v_forest, 'forest', _a_forest),
    'water': LayerSpec(_v_water, 'water', _a_water),
    'collision': LayerSpec(_v_collision, 'collision', _a_collision),
    'entities': LayerSpec(_v_entities, 'entities', _a_entities),
    'buildings': LayerSpec(_v_buildings, 'buildings', _a_buildings),
    'zones': LayerSpec(_v_zones, 'zones', _a_zones),   # people zones move NPCs to venue anchors
}


# ---------------------------------------------------------------- load / save / apply

def empty():
    return {'version': VERSION, 'meta': {}, 'layers': {}}


def migrate(data):
    """Bring older versions forward. v1 is the first version; keep this as the hook."""
    data = copy.deepcopy(data)
    data.setdefault('version', VERSION)
    data.setdefault('meta', {})
    data.setdefault('layers', {})
    return data


def validate(data):
    """Return a list of human-readable errors (empty list = valid)."""
    if not isinstance(data, dict):
        return ['edits must be a JSON object']
    errs = []
    v = data.get('version', VERSION)
    if not isinstance(v, int) or v < 1:
        errs.append('version must be a positive integer')
    elif v > VERSION:
        errs.append(f'version {v} is newer than this tool understands ({VERSION}); update the code')
    if not isinstance(data.get('meta', {}), dict):
        errs.append('meta must be an object')
    layers = data.get('layers', {})
    if not isinstance(layers, dict):
        return errs + ['layers must be an object']
    for name, layer in layers.items():
        spec = LAYERS.get(name)
        if spec is None:
            continue            # unknown layers are preserved untouched (written by a newer editor)
        if not isinstance(layer, dict):
            errs.append(f'layers.{name}: must be an object')
            continue
        errs += spec.validate(layer, f'layers.{name}')
    return errs


def unknown_layers(data):
    return sorted(k for k in data.get('layers', {}) if k not in LAYERS)


def load(path=None):
    path = path or os.environ.get('ARK_EDITS') or DEFAULT_PATH
    if not os.path.exists(path):
        return empty()
    with open(path, encoding='utf-8') as f:
        data = migrate(json.load(f))
    errs = validate(data)
    if errs:
        raise ValueError(f'{path} is invalid:\n  ' + '\n  '.join(errs))
    return data


def save(data, path=None):
    path = path or os.environ.get('ARK_EDITS') or DEFAULT_PATH
    data = migrate(data)
    errs = validate(data)
    if errs:
        raise ValueError('refusing to save invalid edits:\n  ' + '\n  '.join(errs))
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=d, prefix='.edits-', suffix='.tmp')
    with os.fdopen(fd, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write('\n')
    os.replace(tmp, path)
    return path


def apply(stage, data, ctx):
    """Apply every layer registered for `stage` to the generator context (in place)."""
    for name, spec in LAYERS.items():
        if spec.stage == stage and spec.apply and name in data.get('layers', {}):
            spec.apply(data['layers'][name], ctx)
    return ctx


def is_empty(data):
    return not any(v for v in data.get('layers', {}).values())


if __name__ == '__main__':
    import sys
    d = load(sys.argv[1] if len(sys.argv) > 1 else None)
    print('valid; layers:', {k: (len(v) if isinstance(v, (list, dict)) else v) for k, v in d['layers'].items()},
          '| unknown:', unknown_layers(d))
